name: Ruby form

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.2.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint

      - name: Run test
        run: make test
